name: logger
version: 0.0.2
description: Dart gRPC client for Logger
repository: https://github.com/DazWilkin/dart-grpc-logger

environment:
  sdk: ">=3.0.5"

dependencies:
  async: ^2.11.0
  fixnum: ^1.1.0
  grpc: ^3.2.2
  protobuf: ^3.0.0
